In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
path="/content/drive/MyDrive/DataScience/diabetes_dataset.csv"
df = pd.read_csv(path)
print(df)

     Column1  Column2  Column3  Column4  Column4.1  Column5  Column6  Column7  \
0        NaN      NaN      NaN      NaN        NaN      NaN      NaN      NaN
1        NaN      NaN      NaN      NaN        NaN      NaN      NaN      NaN
2        6.0    148.0     72.0     35.0        0.0     33.6    0.627     50.0
3        1.0     85.0     66.0     29.0        0.0     26.6    0.351     31.0
4        8.0    183.0     64.0      0.0        0.0     23.3    0.672     32.0
..       ...      ...      ...      ...        ...      ...      ...      ...
793     10.0    101.0     76.0     48.0      180.0     32.9    0.171     63.0
794      2.0    122.0     70.0     27.0        0.0     36.8    0.340     27.0
795      5.0    121.0     72.0     23.0      112.0     26.2    0.245     30.0
796      1.0    126.0     60.0      0.0        0.0     30.1    0.349     47.0
797      1.0     93.0     70.0     31.0        0.0     30.4    0.315     23.0

     Column8     Cclumn9
0        NaN         NaN
1        NaN         NaN
2        1.0    1/2/1960
3        0.0  11/12/1961
4        1.0   21/2/1962
..       ...         ...
793      0.0         NaN
794      0.0         NaN
795      0.0         NaN
796      1.0         NaN
797      0.0         NaN

[798 rows x 10 columns]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df.rename(columns={"Column1":'Number_of_Pregnancies',"Column2":"Glucose","Column3" : "BloodPressure", "Column4":"SkinThickness",
                   "Column4.1":"Insulin","Column5":"BMI","Column6":"DiabetesPedigreeFunction","Column7":"Age","Column8":"Outcome","Cclumn9":"DOB"},inplace=True)

In [ ]:
df.head()

,Number_of_Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,DOB
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6.0,148.0,72.0,35.0,0.0,33.6,0.627,50.0,1.0,1/2/1960
3,1.0,85.0,66.0,29.0,0.0,26.6,0.351,31.0,0.0,11/12/1961
4,8.0,183.0,64.0,0.0,0.0,23.3,0.672,32.0,1.0,21/2/1962

In [ ]:
#Original Data Types
df.dtypes

Number_of_Pregnancies       float64
Glucose                     float64
BloodPressure               float64
SkinThickness               float64
Insulin                     float64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                         float64
Outcome                     float64
DOB                          object
dtype: object

In [ ]:
#After Data Type conversion
df['Outcome'] = df['Outcome'].astype(str)
df.dtypes

Number_of_Pregnancies       float64
Glucose                     float64
BloodPressure               float64
SkinThickness               float64
Insulin                     float64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                         float64
Outcome                      object
DOB                          object
dtype: object

In [ ]:

# Display the DataFrame after the conversion
print("\nDataFrame after converting 'Age' column to int:")
print(df)

DataFrame after converting 'Age' column to int:
     Number_of_Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  \
0                      NaN      NaN            NaN            NaN      NaN
1                      NaN      NaN            NaN            NaN      NaN
2                      6.0    148.0           72.0           35.0      0.0
3                      1.0     85.0           66.0           29.0      0.0
4                      8.0    183.0           64.0            0.0      0.0
..                     ...      ...            ...            ...      ...
793                   10.0    101.0           76.0           48.0    180.0
794                    2.0    122.0           70.0           27.0      0.0
795                    5.0    121.0           72.0           23.0    112.0
796                    1.0    126.0           60.0            0.0      0.0
797                    1.0     93.0           70.0           31.0      0.0

      BMI  DiabetesPedigreeFunction   Age Outcome         DOB
0     NaN                       NaN   NaN     nan         NaN
1     NaN                       NaN   NaN     nan         NaN
2    33.6                     0.627  50.0     1.0    1/2/1960
3    26.6                     0.351  31.0     0.0  11/12/1961
4    23.3                     0.672  32.0     1.0   21/2/1962
..    ...                       ...   ...     ...         ...
793  32.9                     0.171  63.0     0.0         NaN
794  36.8                     0.340  27.0     0.0         NaN
795  26.2                     0.245  30.0     0.0         NaN
796  30.1                     0.349  47.0     1.0         NaN
797  30.4                     0.315  23.0     0.0         NaN

[798 rows x 10 columns]

In [ ]:
print(df.isnull().sum())

Number_of_Pregnancies        26
Glucose                      26
BloodPressure                26
SkinThickness                26
Insulin                      26
BMI                          26
DiabetesPedigreeFunction     26
Age                          26
Outcome                       0
DOB                         746
dtype: int64

In [ ]:
print(df['DOB'].isnull().sum())

746

In [ ]:
# Remove rows with missing values in a specific column
df_cleaned = df.dropna(subset=['DOB'])

In [ ]:
df['DOB'].fillna("1/9/1973", inplace=True)

In [ ]:
print(df)

     Number_of_Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  \
0                      NaN      NaN            NaN            NaN      NaN
1                      NaN      NaN            NaN            NaN      NaN
2                      6.0    148.0           72.0           35.0      0.0
3                      1.0     85.0           66.0           29.0      0.0
4                      8.0    183.0           64.0            0.0      0.0
..                     ...      ...            ...            ...      ...
793                   10.0    101.0           76.0           48.0    180.0
794                    2.0    122.0           70.0           27.0      0.0
795                    5.0    121.0           72.0           23.0    112.0
796                    1.0    126.0           60.0            0.0      0.0
797                    1.0     93.0           70.0           31.0      0.0

      BMI  DiabetesPedigreeFunction   Age Outcome         DOB
0     NaN                       NaN   NaN     nan    1/9/1973
1     NaN                       NaN   NaN     nan    1/9/1973
2    33.6                     0.627  50.0     1.0    1/2/1960
3    26.6                     0.351  31.0     0.0  11/12/1961
4    23.3                     0.672  32.0     1.0   21/2/1962
..    ...                       ...   ...     ...         ...
793  32.9                     0.171  63.0     0.0    1/9/1973
794  36.8                     0.340  27.0     0.0    1/9/1973
795  26.2                     0.245  30.0     0.0    1/9/1973
796  30.1                     0.349  47.0     1.0    1/9/1973
797  30.4                     0.315  23.0     0.0    1/9/1973

[798 rows x 10 columns]

In [ ]:
# Number of rows before dropping empty rows
num_rows = len(df)
print("Number of rows:", num_rows)

Number of rows: 798

In [ ]:
# Identify missing values and sum them by row
empty_rows = df.isnull().sum(axis=1)

num_empty_rows = (empty_rows > 0).sum()

print("Number of empty rows:", num_empty_rows)

Number of empty rows: 26

In [ ]:
df.dropna(inplace=True)

In [ ]:
# Number of rows before dropping empty rows
num_rows = len(df)
print("Number of rows:", num_rows)

Number of rows: 772

In [ ]:
duplicate_rows = df[df.duplicated()]
print("Rows with duplicate values:")
print(duplicate_rows)

Rows with duplicate values:
    Number_of_Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  \
5                     8.0    183.0           64.0            0.0      0.0
10                    3.0     78.0           50.0           32.0     88.0
18                   10.0    168.0           74.0            0.0      0.0
24                    0.0    118.0           84.0           47.0    230.0

     BMI  DiabetesPedigreeFunction   Age Outcome        DOB
5   23.3                     0.672  32.0     1.0  21/2/1962
10  31.0                     0.248  26.0     1.0  18/2/1965
18  38.0                     0.537  34.0     1.0  11/2/1975
24  45.8                     0.551  31.0     1.0  31/2/1965

In [ ]:
df.head(30)

,Number_of_Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,DOB
2,6.0,148.0,72.0,35.0,0.0,33.6,0.627,50.0,1.0,1/2/1960
3,1.0,85.0,66.0,29.0,0.0,26.6,0.351,31.0,0.0,11/12/1961
4,8.0,183.0,64.0,0.0,0.0,23.3,0.672,32.0,1.0,21/2/1962
5,8.0,183.0,64.0,0.0,0.0,23.3,0.672,32.0,1.0,21/2/1962
6,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0,1/9/1973
7,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0,11/5/1965
8,5.0,116.0,74.0,0.0,0.0,25.6,0.201,30.0,0.0,11/6/1965
9,3.0,78.0,50.0,32.0,88.0,31.0,0.248,26.0,1.0,18/2/1965
10,3.0,78.0,50.0,32.0,88.0,31.0,0.248,26.0,1.0,18/2/1965
11,10.0,115.0,0.0,0.0,0.0,35.3,0.134,29.0,0.0,11/7/1975
12,2.0,197.0,70.0,45.0,543.0,30.5,0.158,53.0,1.0,11/12/1961
13,8.0,125.0,96.0,0.0,0.0,0.0,0.232,54.0,1.0,11/2/1965
16,4.0,110.0,92.0,0.0,0.0,37.6,0.191,30.0,0.0,11/12/1963
17,10.0,168.0,74.0,0.0,0.0,38.0,0.537,34.0,1.0,11/2/1975
18,10.0,168.0,74.0,0.0,0.0,38.0,0.537,34.0,1.0,11/2/1975
19,10.0,139.0,80.0,0.0,0.0,27.1,1.441,57.0,0.0,5/2/1961
20,1.0,189.0,60.0,23.0,846.0,30.1,0.398,59.0,1.0,1/4/1969
21,5.0,166.0,72.0,19.0,175.0,25.8,0.587,51.0,1.0,17/2/1965
22,7.0,100.0,0.0,0.0,0.0,30.0,0.484,32.0,1.0,12/2/1965
23,0.0,118.0,84.0,47.0,230.0,45.8,0.551,31.0,1.0,31/2/1965
24,0.0,118.0,84.0,47.0,230.0,45.8,0.551,31.0,1.0,31/2/1965
25,7.0,107.0,74.0,0.0,0.0,29.6,0.254,31.0,1.0,17/2/1965
26,1.0,103.0,30.0,38.0,83.0,43.3,0.183,33.0,0.0,21/2/1967
27,1.0,115.0,70.0,30.0,96.0,34.6,0.529,32.0,1.0,11/12/1965
28,3.0,126.0,88.0,41.0,235.0,39.3,0.704,27.0,0.0,11/2/1965
29,8.0,99.0,84.0,0.0,0.0,35.4,0.388,50.0,0.0,11/2/1965
30,7.0,196.0,90.0,0.0,0.0,39.8,0.451,41.0,1.0,11/2/1965
31,9.0,119.0,80.0,35.0,0.0,29.0,0.263,29.0,1.0,11/2/1965
32,11.0,143.0,94.0,33.0,146.0,36.6,0.254,51.0,1.0,11/2/1965
38,10.0,125.0,70.0,26.0,115.0,31.1,0.205,41.0,1.0,11/2/1965

In [ ]:
# remove duplicate rows based on all columns
df.drop_duplicates(inplace=True)

df.head(30)

,Number_of_Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,DOB
2,6.0,148.0,72.0,35.0,0.0,33.6,0.627,50.0,1.0,1/2/1960
3,1.0,85.0,66.0,29.0,0.0,26.6,0.351,31.0,0.0,11/12/1961
4,8.0,183.0,64.0,0.0,0.0,23.3,0.672,32.0,1.0,21/2/1962
6,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0,1/9/1973
7,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0,11/5/1965
8,5.0,116.0,74.0,0.0,0.0,25.6,0.201,30.0,0.0,11/6/1965
9,3.0,78.0,50.0,32.0,88.0,31.0,0.248,26.0,1.0,18/2/1965
11,10.0,115.0,0.0,0.0,0.0,35.3,0.134,29.0,0.0,11/7/1975
12,2.0,197.0,70.0,45.0,543.0,30.5,0.158,53.0,1.0,11/12/1961
13,8.0,125.0,96.0,0.0,0.0,0.0,0.232,54.0,1.0,11/2/1965
16,4.0,110.0,92.0,0.0,0.0,37.6,0.191,30.0,0.0,11/12/1963
17,10.0,168.0,74.0,0.0,0.0,38.0,0.537,34.0,1.0,11/2/1975
19,10.0,139.0,80.0,0.0,0.0,27.1,1.441,57.0,0.0,5/2/1961
20,1.0,189.0,60.0,23.0,846.0,30.1,0.398,59.0,1.0,1/4/1969
21,5.0,166.0,72.0,19.0,175.0,25.8,0.587,51.0,1.0,17/2/1965
22,7.0,100.0,0.0,0.0,0.0,30.0,0.484,32.0,1.0,12/2/1965
23,0.0,118.0,84.0,47.0,230.0,45.8,0.551,31.0,1.0,31/2/1965
25,7.0,107.0,74.0,0.0,0.0,29.6,0.254,31.0,1.0,17/2/1965
26,1.0,103.0,30.0,38.0,83.0,43.3,0.183,33.0,0.0,21/2/1967
27,1.0,115.0,70.0,30.0,96.0,34.6,0.529,32.0,1.0,11/12/1965
28,3.0,126.0,88.0,41.0,235.0,39.3,0.704,27.0,0.0,11/2/1965
29,8.0,99.0,84.0,0.0,0.0,35.4,0.388,50.0,0.0,11/2/1965
30,7.0,196.0,90.0,0.0,0.0,39.8,0.451,41.0,1.0,11/2/1965
31,9.0,119.0,80.0,35.0,0.0,29.0,0.263,29.0,1.0,11/2/1965
32,11.0,143.0,94.0,33.0,146.0,36.6,0.254,51.0,1.0,11/2/1965
38,10.0,125.0,70.0,26.0,115.0,31.1,0.205,41.0,1.0,11/2/1965
39,7.0,147.0,76.0,0.0,0.0,39.4,0.257,43.0,1.0,11/2/1965
40,1.0,97.0,66.0,15.0,140.0,23.2,0.487,22.0,0.0,11/2/1965
41,13.0,145.0,82.0,19.0,110.0,22.2,0.245,57.0,0.0,11/2/1965
42,5.0,117.0,92.0,0.0,0.0,34.1,0.337,38.0,0.0,11/2/1965

In [ ]:
#Average Age of Diabities Patient
average_age = df['Age'].mean()

print("Average Age of Patient:", average_age)

Average Age of Patient: 33.240885416666664

In [ ]:
max_age = df['Age'].max()
min_age = df['Age'].min()

# Display the results
print("Maximum Age of Diabities an Patient:", max_age)
print("Minimum Age of Diabities an Patient:", min_age)

Maximum Age of Diabities an Patient: 81.0
Minimum Age of Diabities an Patient: 21.0

In [ ]:
mode_age = df['Outcome'].mode()

# Display the most frequent value
print("Most frequent Outcome:", mode_age.values[0])

Most frequent Outcome: 0.0

In [ ]:
print("Dataset before dropping DOB Column",df)

Dataset before dropping DOB Column      Number_of_Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  \
2                      6.0    148.0           72.0           35.0      0.0
3                      1.0     85.0           66.0           29.0      0.0
4                      8.0    183.0           64.0            0.0      0.0
6                      1.0     89.0           66.0           23.0     94.0
7                      0.0    137.0           40.0           35.0    168.0
..                     ...      ...            ...            ...      ...
793                   10.0    101.0           76.0           48.0    180.0
794                    2.0    122.0           70.0           27.0      0.0
795                    5.0    121.0           72.0           23.0    112.0
796                    1.0    126.0           60.0            0.0      0.0
797                    1.0     93.0           70.0           31.0      0.0

      BMI  DiabetesPedigreeFunction   Age Outcome         DOB
2    33.6                     0.627  50.0     1.0    1/2/1960
3    26.6                     0.351  31.0     0.0  11/12/1961
4    23.3                     0.672  32.0     1.0   21/2/1962
6    28.1                     0.167  21.0     0.0    1/9/1973
7    43.1                     2.288  33.0     1.0   11/5/1965
..    ...                       ...   ...     ...         ...
793  32.9                     0.171  63.0     0.0    1/9/1973
794  36.8                     0.340  27.0     0.0    1/9/1973
795  26.2                     0.245  30.0     0.0    1/9/1973
796  30.1                     0.349  47.0     1.0    1/9/1973
797  30.4                     0.315  23.0     0.0    1/9/1973

[768 rows x 10 columns]

In [ ]:
df.drop('DOB', axis=1, inplace=True)

In [ ]:
print("Dataset after dropping DOB Column",df)

Dataset after dropping DOB Column      Number_of_Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  \
2                      6.0    148.0           72.0           35.0      0.0
3                      1.0     85.0           66.0           29.0      0.0
4                      8.0    183.0           64.0            0.0      0.0
6                      1.0     89.0           66.0           23.0     94.0
7                      0.0    137.0           40.0           35.0    168.0
..                     ...      ...            ...            ...      ...
793                   10.0    101.0           76.0           48.0    180.0
794                    2.0    122.0           70.0           27.0      0.0
795                    5.0    121.0           72.0           23.0    112.0
796                    1.0    126.0           60.0            0.0      0.0
797                    1.0     93.0           70.0           31.0      0.0

      BMI  DiabetesPedigreeFunction   Age Outcome
2    33.6                     0.627  50.0     1.0
3    26.6                     0.351  31.0     0.0
4    23.3                     0.672  32.0     1.0
6    28.1                     0.167  21.0     0.0
7    43.1                     2.288  33.0     1.0
..    ...                       ...   ...     ...
793  32.9                     0.171  63.0     0.0
794  36.8                     0.340  27.0     0.0
795  26.2                     0.245  30.0     0.0
796  30.1                     0.349  47.0     1.0
797  30.4                     0.315  23.0     0.0

[768 rows x 9 columns]

In [ ]:
df['Age'] = df['Age'].astype(int)
df['Number_of_Pregnancies'] = df['Number_of_Pregnancies'].astype(int)
df.dtypes

Number_of_Pregnancies         int64
Glucose                     float64
BloodPressure               float64
SkinThickness               float64
Insulin                     float64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                      object
dtype: object

In [ ]:
print("Dataset before sorting",df)

Dataset before sorting      Number_of_Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  \
2                        6    148.0           72.0           35.0      0.0
3                        1     85.0           66.0           29.0      0.0
4                        8    183.0           64.0            0.0      0.0
6                        1     89.0           66.0           23.0     94.0
7                        0    137.0           40.0           35.0    168.0
..                     ...      ...            ...            ...      ...
793                     10    101.0           76.0           48.0    180.0
794                      2    122.0           70.0           27.0      0.0
795                      5    121.0           72.0           23.0    112.0
796                      1    126.0           60.0            0.0      0.0
797                      1     93.0           70.0           31.0      0.0

      BMI  DiabetesPedigreeFunction  Age Outcome
2    33.6                     0.627   50     1.0
3    26.6                     0.351   31     0.0
4    23.3                     0.672   32     1.0
6    28.1                     0.167   21     0.0
7    43.1                     2.288   33     1.0
..    ...                       ...  ...     ...
793  32.9                     0.171   63     0.0
794  36.8                     0.340   27     0.0
795  26.2                     0.245   30     0.0
796  30.1                     0.349   47     1.0
797  30.4                     0.315   23     0.0

[768 rows x 9 columns]

In [ ]:
df_sorted = df.apply(lambda x: x.sort_values().values)

print("\nDataFrame with columns sorted in ascending order:")
print(df_sorted)

DataFrame with columns sorted in ascending order:
     Number_of_Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  \
2                        0      0.0            0.0            0.0      0.0
3                        0      0.0            0.0            0.0      0.0
4                        0      0.0            0.0            0.0      0.0
6                        0      0.0            0.0            0.0      0.0
7                        0      0.0            0.0            0.0      0.0
..                     ...      ...            ...            ...      ...
793                     13    197.0          110.0           54.0    579.0
794                     14    197.0          110.0           56.0    600.0
795                     14    197.0          110.0           60.0    680.0
796                     15    198.0          114.0           63.0    744.0
797                     17    199.0          122.0           99.0    846.0

      BMI  DiabetesPedigreeFunction  Age Outcome
2     0.0                     0.078   21     0.0
3     0.0                     0.084   21     0.0
4     0.0                     0.085   21     0.0
6     0.0                     0.085   21     0.0
7     0.0                     0.088   21     0.0
..    ...                       ...  ...     ...
793  53.2                     1.893   69     1.0
794  55.0                     2.137   69     1.0
795  57.3                     2.288   70     1.0
796  59.4                     2.329   72     1.0
797  67.1                     2.420   81     1.0

[768 rows x 9 columns]

In [ ]:
df_sorted.head(30)

,Number_of_Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
2,0,0.0,0.0,0.0,0.0,0.0,0.078,21,0.0
3,0,0.0,0.0,0.0,0.0,0.0,0.084,21,0.0
4,0,0.0,0.0,0.0,0.0,0.0,0.085,21,0.0
6,0,0.0,0.0,0.0,0.0,0.0,0.085,21,0.0
7,0,0.0,0.0,0.0,0.0,0.0,0.088,21,0.0
8,0,44.0,0.0,0.0,0.0,0.0,0.088,21,0.0
9,0,56.0,0.0,0.0,0.0,0.0,0.089,21,0.0
11,0,57.0,0.0,0.0,0.0,0.0,0.092,21,0.0
12,0,57.0,0.0,0.0,0.0,0.0,0.096,21,0.0
13,0,61.0,0.0,0.0,0.0,0.0,0.100,21,0.0
16,0,62.0,0.0,0.0,0.0,0.0,0.101,21,0.0
17,0,65.0,0.0,0.0,0.0,18.2,0.102,21,0.0
19,0,67.0,0.0,0.0,0.0,18.2,0.107,21,0.0
20,0,68.0,0.0,0.0,0.0,18.2,0.108,21,0.0
21,0,68.0,0.0,0.0,0.0,18.4,0.115,21,0.0
22,0,68.0,0.0,0.0,0.0,19.1,0.118,21,0.0
23,0,71.0,0.0,0.0,0.0,19.3,0.121,21,0.0
25,0,71.0,0.0,0.0,0.0,19.4,0.121,21,0.0
26,0,71.0,0.0,0.0,0.0,19.5,0.122,21,0.0
27,0,71.0,0.0,0.0,0.0,19.5,0.123,21,0.0
28,0,72.0,0.0,0.0,0.0,19.6,0.126,21,0.0
29,0,73.0,0.0,0.0,0.0,19.6,0.126,21,0.0
30,0,73.0,0.0,0.0,0.0,19.6,0.127,21,0.0
31,0,73.0,0.0,0.0,0.0,19.9,0.127,21,0.0
32,0,74.0,0.0,0.0,0.0,20.0,0.128,21,0.0
38,0,74.0,0.0,0.0,0.0,20.1,0.128,21,0.0
39,0,74.0,0.0,0.0,0.0,20.4,0.129,21,0.0
40,0,74.0,0.0,0.0,0.0,20.4,0.129,21,0.0
41,0,75.0,0.0,0.0,0.0,20.8,0.130,21,0.0
42,0,75.0,0.0,0.0,0.0,20.8,0.133,21,0.0

In [ ]:
# output_file_path = 'Desktop/modified_dataset.csv'
df.to_csv("C:\\Users\\HP\\Desktop\\filter_dataset.csv")
df=pd.read_csv("C:\\Users\\HP\\Desktop\\filter_dataset.csv")
print(df)

     Unnamed: 0  Number_of_Pregnancies  Glucose  BloodPressure  SkinThickness  \
0             2                      6    148.0           72.0           35.0
1             3                      1     85.0           66.0           29.0
2             4                      8    183.0           64.0            0.0
3             6                      1     89.0           66.0           23.0
4             7                      0    137.0           40.0           35.0
..          ...                    ...      ...            ...            ...
763         793                     10    101.0           76.0           48.0
764         794                      2    122.0           70.0           27.0
765         795                      5    121.0           72.0           23.0
766         796                      1    126.0           60.0            0.0
767         797                      1     93.0           70.0           31.0

     Insulin   BMI  DiabetesPedigreeFunction  Age  Outcome
0        0.0  33.6                     0.627   50      1.0
1        0.0  26.6                     0.351   31      0.0
2        0.0  23.3                     0.672   32      1.0
3       94.0  28.1                     0.167   21      0.0
4      168.0  43.1                     2.288   33      1.0
..       ...   ...                       ...  ...      ...
763    180.0  32.9                     0.171   63      0.0
764      0.0  36.8                     0.340   27      0.0
765    112.0  26.2                     0.245   30      0.0
766      0.0  30.1                     0.349   47      1.0
767      0.0  30.4                     0.315   23      0.0

[768 rows x 10 columns]